fos_rest:
    body_listener: true
    exception:
        enabled: true
        exception_controller: App\Controller\ExceptionController::exception
    format_listener:
        rules:
            path: '^/'
            priorities: ['json', 'xml']
            fallback_format: 'json'
            prefer_extension: true
    param_fetcher_listener:  true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
