lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(JWT_SECRET_KEY)%'
    public_key:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'

gesdinet_jwt_refresh_token:
    user_provider: app.user_provider
    refresh_token_entity: 'App\Entity\Security\JwtRefreshToken'
    ttl: 604800
    ttl_update: true
