lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'

gesdinet_jwt_refresh_token:
    user_provider: app.user_provider
    refresh_token_entity: 'App\Entity\Security\JwtRefreshToken'
    ttl: 604800
    ttl_update: true
