security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        web_service:
            id: app.user_provider

    encoders:
        App\Entity\Security\User:  auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        login:
            pattern:  ^/api/authentication/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/authentication/login
                username_parameter:       username
                password_parameter:       password
                success_handler:          app.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        refresh:
            pattern:  ^/api/authentication/refresh
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            switch_user: { role: ROLE_SUPER_ADMIN }
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/authentication/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/authentication/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
