version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./dev/data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: backend
      MYSQL_USER: myadmin
      MYSQL_PASSWORD: mypassword
  php:
    image: php:7.3-fpm
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "9000:9000"
  nginx:
    image: nginx:mainline
    volumes:
      - ./:/var/www/html:cached
      - ./.docker-nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - "8000:80"
  composer:
    image: composer
    restart: "no"
    command: install
    volumes:
      - ./:/app
