gesdinet_jwt_refresh_token:
    path:     /api/authentication/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken::refresh }

api_authentication_login:
    path: /api/authentication/login

default:
    resource: ../src/Controller
    type: annotation
    defaults: { _format: json }
    prefix: /

api:
    resource: ../src/Controller/Api
    type: annotation
    defaults: { _format: json }
    prefix: /api

